In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array (my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

In [7]:
my_lists = [my_list1, my_list2]

In [8]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
my_array2 = np.array (my_lists)

In [10]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
my_array2.shape

(2L, 4L)

In [12]:
my_array2.dtype

dtype('int32')

In [13]:
np.zeros(6)

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
my_zero_arrays = np.zeros(6)

In [15]:
my_zero_arrays.dtype

dtype('float64')

In [17]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [18]:
np.empty([6,6])

array([[  1.03753786e-322,   5.71153009e-316,   5.71153088e-316,
          5.71153365e-316,   0.00000000e+000,   0.00000000e+000],
       [  5.74137165e-316,   6.36598737e-314,  -1.94703601e-048,
          0.00000000e+000,   0.00000000e+000,   2.45217428e-316],
       [  5.71153365e-316,   5.71153365e-316,   5.71153365e-316,
          2.12199579e-314,   0.00000000e+000,   4.09536963e-312],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   9.88131292e-324,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   3.51675057e-316,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   4.94065646e-324,   5.71153365e-316]])

In [19]:
np.empty(5)

array([  2.73280357e-316,   2.12562337e-316,   1.58504915e-316,
         1.58522109e-316,   2.50022169e-315])

In [20]:
np.empty([5])

array([ 0.,  0.,  0.,  0.,  0.])

In [21]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [23]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [25]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [26]:
np.arange(3,49,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47])