In [1]:
import numpy as np

In [4]:
arr = np.arange (1,11)

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr [5]

6

In [7]:
arr [3:8]

array([4, 5, 6, 7, 8])

In [8]:
arr [0:4]

array([1, 2, 3, 4])

In [9]:
arr [1:4]

array([2, 3, 4])

In [11]:
arr [1:9] = 1888

In [12]:
arr

array([   1, 1888, 1888, 1888, 1888, 1888, 1888, 1888, 1888,   10])

In [13]:
arr = np.arange(0,10)

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
slice_of_arr = arr [0:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_arr [:] = 99 

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [20]:
arr_copy = arr.copy()

In [21]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [24]:
arr_2d = np.array (([5,10,15],[20,25,30], [35,40,45]))

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[1]

array([20, 25, 30])

In [28]:
arr_2d[2,2]

45

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d[:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[:1,]

array([[ 5, 10, 15]])

In [32]:
arr_2d[:0,]

array([], shape=(0L, 3L), dtype=int32)

In [33]:
arr_2d[:2,]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [34]:
arr_2d[:2,:1]

array([[ 5],
       [20]])

In [35]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr_2d[2,2]

45

In [40]:
arr_length = arr_2d.shape[1]

In [41]:
arr_length

3L

In [50]:
for i in range (arr_length):
arr_2d[i]= i

IndentationError: expected an indented block (<ipython-input-50-5827ec0a4ad2>, line 2)