In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 

In [3]:
points = np.arange(-5, 5, 0.01)

In [4]:
points

array([ -5.00000000e+00,  -4.99000000e+00,  -4.98000000e+00,
        -4.97000000e+00,  -4.96000000e+00,  -4.95000000e+00,
        -4.94000000e+00,  -4.93000000e+00,  -4.92000000e+00,
        -4.91000000e+00,  -4.90000000e+00,  -4.89000000e+00,
        -4.88000000e+00,  -4.87000000e+00,  -4.86000000e+00,
        -4.85000000e+00,  -4.84000000e+00,  -4.83000000e+00,
        -4.82000000e+00,  -4.81000000e+00,  -4.80000000e+00,
        -4.79000000e+00,  -4.78000000e+00,  -4.77000000e+00,
        -4.76000000e+00,  -4.75000000e+00,  -4.74000000e+00,
        -4.73000000e+00,  -4.72000000e+00,  -4.71000000e+00,
        -4.70000000e+00,  -4.69000000e+00,  -4.68000000e+00,
        -4.67000000e+00,  -4.66000000e+00,  -4.65000000e+00,
        -4.64000000e+00,  -4.63000000e+00,  -4.62000000e+00,
        -4.61000000e+00,  -4.60000000e+00,  -4.59000000e+00,
        -4.58000000e+00,  -4.57000000e+00,  -4.56000000e+00,
        -4.55000000e+00,  -4.54000000e+00,  -4.53000000e+00,
        -4.52000000e+00,

In [5]:
dx,dy = np.meshgrid(points, points)

In [6]:
dx,dy

(array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        ..., 
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]]),
 array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
        [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
        [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
        ..., 
        [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
        [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
        [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]]))

In [7]:
dx

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [8]:
dy

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [9]:
z= (np.sin(dx) + np.sin(dy))

z

array([[  1.91784855e+00,   1.92063718e+00,   1.92332964e+00, ...,
         -8.07710558e-03,  -5.48108704e-03,  -2.78862876e-03],
       [  1.92063718e+00,   1.92342581e+00,   1.92611827e+00, ...,
         -5.28847682e-03,  -2.69245827e-03,  -5.85087534e-14],
       [  1.92332964e+00,   1.92611827e+00,   1.92881072e+00, ...,
         -2.59601854e-03,  -5.63993297e-14,   2.69245827e-03],
       ..., 
       [ -8.07710558e-03,  -5.28847682e-03,  -2.59601854e-03, ...,
         -1.93400276e+00,  -1.93140674e+00,  -1.92871428e+00],
       [ -5.48108704e-03,  -2.69245827e-03,  -5.63993297e-14, ...,
         -1.93140674e+00,  -1.92881072e+00,  -1.92611827e+00],
       [ -2.78862876e-03,  -5.85087534e-14,   2.69245827e-03, ...,
         -1.92871428e+00,  -1.92611827e+00,  -1.92342581e+00]])

In [11]:
plt.imshow(z)

In [12]:
plt.imshow(z)
plt.colorbar()
plt.title('plot for sin(x)+sin(y)')

In [13]:
#numpy where

In [14]:
A=np.array([1,2,3,4])

In [15]:
B=np.array([100,200,300,400])

In [16]:
condition = np.array([True,True,False,False])

In [19]:
answer = [(A_val if cond else B_val) for A_val, B_val, cond in zip(A, B, condition)]

In [20]:
answer

[1, 2, 300, 400]

In [21]:
answer2= np.where(condition, A, B)

In [22]:
answer2

array([  1,   2, 300, 400])

In [23]:
from numpy.random import randn

In [24]:
arr = randn(5,5)

In [25]:
arr

array([[-1.83399205, -1.09178745,  0.75682433, -0.63710278,  0.52678618],
       [ 1.59814821, -0.01714064, -0.97041972, -0.91127722, -0.17106716],
       [-0.28207922,  2.08105091, -1.57670585, -1.18332834, -0.45417205],
       [ 0.57407448,  0.00349244, -0.26958443, -0.46638018, -1.18390079],
       [-0.35365493, -1.06464871,  0.08932179, -0.86767029,  0.91512725]])

In [26]:
np.where(arr<0,0,arr)

array([[ 0.        ,  0.        ,  0.75682433,  0.        ,  0.52678618],
       [ 1.59814821,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  2.08105091,  0.        ,  0.        ,  0.        ],
       [ 0.57407448,  0.00349244,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.08932179,  0.        ,  0.91512725]])

In [28]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.sum()

45

In [31]:
arr.sum(0)

array([12, 15, 18])

In [32]:
arr.sum(1)

array([ 6, 15, 24])

In [33]:
arr.mean()

5.0

In [34]:
arr.std()

2.5819888974716112

In [35]:
arr.var()

6.666666666666667

In [36]:
bool_arr = np.array([True, False, True])
bool_arr.any()

True

In [37]:
bool_arr.all()

False

In [38]:
#sort
arr = randn (5)
arr

array([ 1.14851283,  3.47039721, -1.06435572, -1.28059278, -0.37565135])

In [39]:
arr.sort()

In [40]:
arr

array([-1.28059278, -1.06435572, -0.37565135,  1.14851283,  3.47039721])

In [41]:
countries = np.array(['France','Germany','USA','Russia', 'USA', 'Mexico', 'Germany'])

In [42]:
countries

array(['France', 'Germany', 'USA', 'Russia', 'USA', 'Mexico', 'Germany'], 
      dtype='|S7')

In [43]:
np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], 
      dtype='|S7')

In [45]:
np.in1d(['France','USA','Sweden'], countries)

array([ True,  True, False], dtype=bool)