In [1]:
import numpy as np

In [2]:
5/2

2

In [3]:
5./2

2.5

In [5]:
from __future__ import division 

In [6]:
5/2

2.5

In [8]:
array1 = np.array ([[1,2,3,4], [8,9,10,11]])

In [9]:
array1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [10]:
array1 * array1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [11]:
array1 - array1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
3/array1

array([[ 3.        ,  1.5       ,  1.        ,  0.75      ],
       [ 0.375     ,  0.33333333,  0.3       ,  0.27272727]])

In [13]:
array1 ^ array1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
array1 **4

array([[    1,    16,    81,   256],
       [ 4096,  6561, 10000, 14641]])