In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-0.75860999, -0.72973228, -0.89017366,  0.03066144,  1.66403627,
        1.88108803,  0.2778304 ,  0.36935195,  0.50284483, -1.27716204])

In [7]:
B = np.random.randn (10)
B

array([ 0.66419773, -0.27563371, -1.17421987, -0.86288246,  0.61154988,
        1.04803896, -1.4722674 ,  0.58768101, -0.0356287 ,  0.57052728])

In [8]:
#binary functions

In [9]:
np.add(A,B)

array([-0.09441227, -1.00536599, -2.06439353, -0.83222101,  2.27558615,
        2.92912699, -1.194437  ,  0.95703296,  0.46721613, -0.70663476])

In [10]:
np.maximum(A,B)

array([ 0.66419773, -0.27563371, -0.89017366,  0.03066144,  1.66403627,
        1.88108803,  0.2778304 ,  0.58768101,  0.50284483,  0.57052728])

In [11]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True